encoder_wavenet:
  embedding_dim: 128
  channels: 128
  kernel_size: 3
  dilation_base: 3
  num_layers: 12

decoder_wavenet:
  channels: 128
  kernel_size: 3
  dilation_base: 3
  num_layers: 12

discriminator:
  channels: 128
  kernel_size: 3
  stride: 2
  num_blocks: 4
  activation: leakyrelu
  batch_norm: true

predictor:
  input_dim: 2
  hidden_dim: 32
  kernel_size: 3
  dropout: 0.1

train:
  batch_size: 32
  learning_rate: 0.0001
  optimizer: Adam
  adam_beta1: 0.5
  adam_beta2: 0.999
  lr_scheduler: halve_every_10_epochs
  total_epoch: 150
  loss_weights:
    wgan: 0.0001
    mse: 1.0
    consistency: 0.01
